server:
  port: ${EVENT_NOTIFICATOR_PORT:8083}

spring:
  application:
    name: event-notificator

  datasource:
    url: ${EVENT_NOTIFICATOR_DB_URL:jdbc:postgresql://localhost:${POSTGRES_EVENT_NOTIFICATOR_PORT:5436}/${POSTGRES_EVENT_NOTIFICATOR_DB:eventNotificationdb}}
    username: ${POSTGRES_EVENT_NOTIFICATOR_USER:event}
    password: ${POSTGRES_EVENT_NOTIFICATOR_PASSWORD:notification}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
    default-schema: public
    liquibase-schema: public

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  cache:
    type: redis

  data:
    redis:
      host: ${EVENT_NOTIFICATOR_REDIS_HOST:localhost}
      port: ${EVENT_NOTIFICATOR_REDIS_PORT:6380}
      timeout: 2s

  kafka:
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:event-notificator-group}
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.IntegerDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: ${KAFKA_TRUSTED_PACKAGES:*}
        spring.json.value.default.type: ${KAFKA_JSON_DEFAULT_TYPE:ru.haritonenko.commonlibs.dto.notification.EventChangeKafkaMessage}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:${KAFKA_HOST_PORT:9092}}

kafka-topic: ${KAFKA_TOPIC_EVENT_CHANGED:event-changed-topic}

app:
  location:
    default-page-size: ${EVENT_NOTIFICATOR_DEFAULT_PAGE_SIZE:5}
    default-page-number: ${EVENT_NOTIFICATOR_DEFAULT_PAGE_NUMBER:0}

  cache:
    default-ttl: ${EVENT_NOTIFICATOR_CACHE_DEFAULT_TTL:30s}
    unread-notifications-ttl: ${EVENT_NOTIFICATOR_CACHE_UNREAD_NOTIFICATIONS_TTL:30s}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  lifetime: ${JWT_LIFETIME_MS:86400000}

springdoc:
  swagger-ui:
    url: /event-notificator-openapi.yaml
    path: /swagger-ui.html

scheduler:
  enabled: ${EVENT_NOTIFICATOR_SCHEDULER_ENABLED:true}
  notifications:
    cleanup-cron: ${EVENT_NOTIFICATOR_NOTIFICATIONS_CLEANUP_CRON:0 */10 * * * *}
    ttl-days: ${EVENT_NOTIFICATOR_NOTIFICATIONS_TTL_DAYS:7}