server:
  port: ${EVENT_MANAGER_PORT:8082}

spring:
  application:
    name: EventManager

  datasource:
    url: ${EVENT_MANAGER_DB_URL:jdbc:postgresql://localhost:${POSTGRES_EVENT_MANAGER_PORT:5435}/${POSTGRES_EVENT_MANAGER_DB:eventdb}}
    username: ${POSTGRES_EVENT_MANAGER_USER:event}
    password: ${POSTGRES_EVENT_MANAGER_PASSWORD:manager}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
    default-schema: public
    liquibase-schema: public

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public

  cache:
    type: redis
  data:
    redis:
      host: ${EVENT_MANAGER_REDIS_HOST:localhost}
      port: ${EVENT_MANAGER_REDIS_PORT:${REDIS_EVENT_MANAGER_PORT:6379}}
      timeout: 2s

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:${KAFKA_HOST_PORT:9092}}

springdoc:
  swagger-ui:
    url: /openapi.yaml
    path: /swagger-ui.html

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

jwt:
  secret-key: ${JWT_SECRET_KEY}
  lifetime: ${JWT_LIFETIME_MS:86400000}

app:
  location:
    default-page-size: ${EVENT_MANAGER_DEFAULT_PAGE_SIZE:5}
    default-page-number: ${EVENT_MANAGER_DEFAULT_PAGE_NUMBER:0}

  cache:
    default-ttl: ${EVENT_MANAGER_CACHE_DEFAULT_TTL:30s}
    events-ttl: ${EVENT_MANAGER_CACHE_EVENTS_TTL:30s}
    locations-ttl: ${EVENT_MANAGER_CACHE_LOCATIONS_TTL:30s}
    registrations-ttl: ${EVENT_MANAGER_CACHE_REGISTRATIONS_TTL:30s}
    users-ttl: ${EVENT_MANAGER_CACHE_USERS_TTL:30s}
    user-booked-events-ttl: ${EVENT_MANAGER_CACHE_USER_BOOKED_EVENTS_TTL:20s}
    user-created-events-ttl: ${EVENT_MANAGER_CACHE_USER_CREATED_EVENTS_TTL:30s}

scheduler:
  enabled: ${EVENT_MANAGER_SCHEDULER_ENABLED:true}
  event-status:
    fixed-delay-ms: ${EVENT_MANAGER_EVENT_STATUS_FIXED_DELAY_MS:60000}

kafka-topic: ${KAFKA_TOPIC_EVENT_CHANGED:event-changed-topic}
