CREATE TABLE IF NOT EXISTS locations
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(40)  NOT NULL,
    address     VARCHAR(30)  NOT NULL,
    capacity    INTEGER      NOT NULL,
    description VARCHAR(100) NOT NULL
);
