CREATE TABLE IF NOT EXISTS events
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(50)    NOT NULL,
    owner_id        BIGINT         NOT NULL,
    location_id     BIGINT         NOT NULL,
    max_places      INTEGER        NOT NULL,
    occupied_places INTEGER        NOT NULL,
    date            VARCHAR(255)   NOT NULL,
    cost            NUMERIC(19, 2) NOT NULL,
    duration        INTEGER        NOT NULL,
    status          VARCHAR(50)    NOT NULL
);

ALTER TABLE events
    ADD CONSTRAINT fk_events_owner
        FOREIGN KEY (owner_id) REFERENCES users (id);

ALTER TABLE events
    ADD CONSTRAINT fk_events_location
        FOREIGN KEY (location_id) REFERENCES locations (id);

CREATE INDEX IF NOT EXISTS ix_events_owner_id ON events (owner_id);
CREATE INDEX IF NOT EXISTS ix_events_location_id ON events (location_id);
