CREATE TABLE IF NOT EXISTS event_registrations
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT      NOT NULL,
    event_id BIGINT      NOT NULL,
    status   VARCHAR(50) NOT NULL
);

ALTER TABLE event_registrations
    ADD CONSTRAINT fk_event_registrations_user
        FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE event_registrations
    ADD CONSTRAINT fk_event_registrations_event
        FOREIGN KEY (event_id) REFERENCES events (id);

CREATE UNIQUE INDEX IF NOT EXISTS uk_event_registrations_user_event
    ON event_registrations (user_id, event_id);

CREATE INDEX IF NOT EXISTS ix_event_registrations_user_id ON event_registrations (user_id);
CREATE INDEX IF NOT EXISTS ix_event_registrations_event_id ON event_registrations (event_id);
