CREATE TABLE IF NOT EXISTS notifications
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    event_id   BIGINT       NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    is_read    BOOLEAN      NOT NULL,
    message    VARCHAR(2000) NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_notifications_user_id ON notifications (user_id);
CREATE INDEX IF NOT EXISTS ix_notifications_event_id ON notifications (event_id);



