CREATE TABLE IF NOT EXISTS notifications
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER       NOT NULL,
    event_id   INTEGER       NOT NULL,
    created_at TIMESTAMP     NOT NULL,
    is_read    BOOLEAN       NOT NULL,
    message    VARCHAR(2000) NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_notifications_user_id ON notifications (user_id);
CREATE INDEX IF NOT EXISTS ix_notifications_event_id ON notifications (event_id);
